services:
  text-to-audio:
    build: 
      context: .
      dockerfile: Dockerfile
    image: text-to-audio:latest
    container_name: text-to-audio-prod
    volumes:
      # Гибкое монтирование данных через переменную окружения
      - ${DATA_PATH:-./data}:/app/data
    env_file:
      - .env.prod
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
