version: '3.8'

services:
  text-to-audio:
    build: .
    container_name: text-to-audio-dev
    volumes:
      # Гибкое монтирование данных через переменную окружения
      - ${DATA_PATH:-./data}:/app/data
      # Временные файлы в именованном volume
      - temp_data:/app/temp
    env_file:
      - .env
    environment:
      # Yandex Cloud авторизация из .env файла
      - YANDEX_KEY_ID=${YANDEX_KEY_ID}
      - YANDEX_SERVICE_ACCOUNT_ID=${YANDEX_SERVICE_ACCOUNT_ID}
      - YANDEX_KEY_ALGORITHM=${YANDEX_KEY_ALGORITHM}
      - YANDEX_PUBLIC_KEY=${YANDEX_PUBLIC_KEY}
      - YANDEX_PRIVATE_KEY=${YANDEX_PRIVATE_KEY}
      # Настройки логирования
      - LOG_LEVEL=${LOG_LEVEL}
      - LOG_FORMAT=${LOG_FORMAT}
      # Директории
      - TEMP_DIR=${TEMP_DIR}
      - INPUT_DIR=${INPUT_DIR}
      - OUTPUT_DIR=${OUTPUT_DIR}
      # Настройки синтеза речи
      - DEFAULT_VOICE=${DEFAULT_VOICE}
      - DEFAULT_ROLE=${DEFAULT_ROLE}
      - DEFAULT_FORMAT=${DEFAULT_FORMAT}
      # Настройки обработки
      - MAX_CHUNK_SIZE=${MAX_CHUNK_SIZE}
      - MAX_RETRIES=${MAX_RETRIES}
      - RETRY_DELAY=${RETRY_DELAY}
      # Настройки rate limiting
      - REQUESTS_PER_SECOND=${REQUESTS_PER_SECOND}
      # Redis для кэширования токенов
      - REDIS_URL=${REDIS_URL}
      - REDIS_ENABLED=${REDIS_ENABLED}
    depends_on:
      - redis
    networks:
      - text-to-audio-network
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: text-to-audio-redis
    volumes:
      - redis_data:/data
    networks:
      - text-to-audio-network
    restart: unless-stopped
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3


volumes:
  temp_data:
    driver: local
  redis_data:
    driver: local

networks:
  text-to-audio-network:
    driver: bridge
