services:
  text-to-audio:
    build: .
    container_name: text-to-audio-dev
    volumes:
      # Гибкое монтирование данных через переменную окружения
      - ${DATA_PATH:-./data}:/app/data
    env_file:
      - .env
    restart: unless-stopped
